require("src.libs.lua.math")
require("src.libs.lua.string")
require("src.libs.lua.table")

require("src.libs.love.animation")
require("src.libs.love.camera")
require("src.libs.love.collision")
require("src.libs.love.color")
require("src.libs.love.data")
require("src.libs.love.physics")
require("src.libs.love.state")
require("src.libs.love.timer")
require("src.libs.love.vector")
